In [1]:
import numpy as np

# Function to read a matrix from the user
def read_matrix():
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    
    matrix = []
    print("Enter the matrix values row-wise:")
    for i in range(rows):
        row = []
        for j in range(cols):
            val = int(input(f"Enter value for element ({i+1},{j+1}): "))
            row.append(val)
        matrix.append(row)
    
    return np.array(matrix)

# Main program
print("Matrix A:")
matrix_a = read_matrix()

print("\nMatrix B:")
matrix_b = read_matrix()

Matrix A:
Enter the number of rows: 2
Enter the number of columns: 2
Enter the matrix values row-wise:
Enter value for element (1,1): 1
Enter value for element (1,2): 2
Enter value for element (2,1): 3
Enter value for element (2,2): 4

Matrix B:
Enter the number of rows: 2
Enter the number of columns: 2
Enter the matrix values row-wise:
Enter value for element (1,1): 5
Enter value for element (1,2): 6
Enter value for element (2,1): 7
Enter value for element (2,2): 8


In [2]:
# 1. Dot Product
dot_product = np.dot(matrix_a, matrix_b)
print("\n1. Dot Product:")
print(dot_product)



1. Dot Product:
[[19 22]
 [43 50]]


In [3]:
# 2. Transpose
transpose_a = np.transpose(matrix_a)
transpose_b = np.transpose(matrix_b)
print("\n2. Transpose of Matrix A:")
print(transpose_a)
print("\nTranspose of Matrix B:")
print(transpose_b)


2. Transpose of Matrix A:
[[1 3]
 [2 4]]

Transpose of Matrix B:
[[5 7]
 [6 8]]


In [4]:
# 3. Trace
trace_a = np.trace(matrix_a)
trace_b = np.trace(matrix_b)
print("\n3. Trace of Matrix A:", trace_a)
print("Trace of Matrix B:", trace_b)


3. Trace of Matrix A: 5
Trace of Matrix B: 13


In [5]:
# 4. Rank
rank_a = np.linalg.matrix_rank(matrix_a)
rank_b = np.linalg.matrix_rank(matrix_b)
print("\n4. Rank of Matrix A:", rank_a)
print("Rank of Matrix B:", rank_b)



4. Rank of Matrix A: 2
Rank of Matrix B: 2


In [6]:
# 5. Determinant
det_a = np.linalg.det(matrix_a)
det_b = np.linalg.det(matrix_b)
print("\n5. Determinant of Matrix A:", det_a)
print("Determinant of Matrix B:", det_b)



5. Determinant of Matrix A: -2.0000000000000004
Determinant of Matrix B: -2.000000000000005


In [7]:
# 6. Inverse
if det_a == 0:
    print("\nMatrix A is singular, and the inverse does not exist.")
else:
    inverse_a = np.linalg.inv(matrix_a)
    print("\n6. Inverse of Matrix A:")
    print(inverse_a)


6. Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
if det_b == 0:
    print("\nMatrix B is singular, and the inverse does not exist.")
else:
    inverse_b = np.linalg.inv(matrix_b)
    print("\nInverse of Matrix B:")
    print(inverse_b)


Inverse of Matrix B:
[[-4.   3. ]
 [ 3.5 -2.5]]


In [9]:
# 7. Eigenvalues and Eigenvectors
eigenvalues_a, eigenvectors_a = np.linalg.eig(matrix_a)
eigenvalues_b, eigenvectors_b = np.linalg.eig(matrix_b)
print("\n7. Eigenvalues and Eigenvectors of Matrix A:")
print("Eigenvalues:")
print(eigenvalues_a)
print("Eigenvectors:")
print(eigenvectors_a)

print("\nEigenvalues and Eigenvectors of Matrix B:")
print("Eigenvalues:")
print(eigenvalues_b)
print("Eigenvectors:")
print(eigenvectors_b)


7. Eigenvalues and Eigenvectors of Matrix A:
Eigenvalues:
[-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Eigenvalues and Eigenvectors of Matrix B:
Eigenvalues:
[-0.15206735 13.15206735]
Eigenvectors:
[[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]
